import { css } from '@emotion/css';
import type { GrafanaTheme2 } from '@grafana/data';

export const getOperationsStyles = (theme: GrafanaTheme2) => ({
  app: css`width:100%;max-width:none;min-width:0;min-height:100%;margin:0;padding:${theme.spacing(1.5)};box-sizing:border-box;color:#edf2f8;background:#0b1019;`,
  header: css`border-bottom:1px solid #2a3444;padding:${theme.spacing(1, 0, 1.5)};`,
  contextRow: css`display:flex;align-items:center;justify-content:space-between;gap:${theme.spacing(1.5)};flex-wrap:wrap;`,
  context: css`display:flex;align-items:center;gap:${theme.spacing(1)};flex-wrap:wrap;color:#aeb9c9;font-size:12px;`,
  eyebrow: css`color:#8391a6;font-size:11px;font-weight:700;letter-spacing:0;`,
  heading: css`margin:${theme.spacing(.5,0,0)};font-size:26px;line-height:1.15;letter-spacing:0;`,
  subtitle: css`margin:${theme.spacing(.5,0,0)};color:#8f9bad;font-size:13px;`,
  meta: css`border:1px solid #2e394a;background:#101722;padding:${theme.spacing(.65,1)};color:#aeb9c9;font-size:11px;`,
  linkState: css`display:inline-flex;align-items:center;gap:6px;color:#8ecfaf;font-size:12px;&::before{content:'';width:7px;height:7px;border-radius:50%;background:currentColor;}`,
  degraded: css`color:#e7ad65;`,
  critical: css`color:#ff7188;`,
  attention: css`color:#e9b05d;`,
  normal: css`color:#5fd39b;`,
  nav: css`display:flex;gap:${theme.spacing(.75)};border-bottom:1px solid #2a3444;padding:${theme.spacing(1.5,0,0)};overflow-x:auto;`,
  navButton: css`border:0;border-bottom:2px solid transparent;background:transparent;color:#92a0b2;padding:${theme.spacing(.85,1)};font-size:13px;cursor:pointer;white-space:nowrap;transition:color .14s ease,border-color .14s ease,background .14s ease;&:hover{color:#e8eef7;background:#121b29;}&:focus-visible{outline:2px solid #4aa3ff;outline-offset:-2px;}`,
  navActive: css`color:#f2f6fb;border-color:#4aa3ff;`,
  roleGroup: css`display:flex;border:1px solid #2e394a;background:#101722;`,
  roleButton: css`border:0;border-right:1px solid #2e394a;background:transparent;color:#93a0b1;padding:${theme.spacing(.65,.9)};font-size:11px;cursor:pointer;&:last-child{border-right:0;}`,
  roleActive: css`background:#1a2b3e;color:#eaf3ff;`,
  workspaceStage: css`width:100%;min-width:0;min-height:620px;padding-top:${theme.spacing(1.5)};`,
  workspaceIntro: css`display:flex;align-items:flex-end;justify-content:space-between;gap:${theme.spacing(2)};border-bottom:1px solid #2b3647;padding:${theme.spacing(0,0,1.5)};@media(max-width:760px){align-items:flex-start;flex-direction:column;}`,
  workspaceTitle: css`margin:${theme.spacing(.4,0,0)};font-size:20px;line-height:1.2;color:#f0f4fa;`,
  workspaceDescription: css`margin:${theme.spacing(.45,0,0)};color:#8e9caf;font-size:12px;`,
  workspaceFocus: css`display:grid;gap:3px;min-width:218px;border-left:2px solid #4aa3ff;padding-left:${theme.spacing(1)};color:#8e9caf;font-size:11px;b{color:#edf2f8;font-size:12px;}small{color:#748398;font-size:11px;}`,
  workspaceEnter: css`width:100%;min-width:0;@keyframes batteryWorkspaceEnter{from{opacity:.12;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}animation:batteryWorkspaceEnter .18s cubic-bezier(.2,.8,.2,1) both;@media(prefers-reduced-motion:reduce){animation:none;}`,
  content: css`display:grid;width:100%;min-width:0;gap:${theme.spacing(1.5)};padding-top:${theme.spacing(1.5)};`,
  priority: css`display:flex;align-items:center;justify-content:space-between;gap:${theme.spacing(1.5)};border:1px solid #7a5c2c;border-left:3px solid #e9b05d;background:#171812;padding:${theme.spacing(1.25,1.5)};`,
  priorityTitle: css`display:flex;align-items:center;gap:${theme.spacing(1)};font-size:14px;font-weight:700;`,
  priorityDetail: css`margin-top:3px;color:#afb8c6;font-size:12px;`,
  grid4: css`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:${theme.spacing(1.5)};@media(max-width:1000px){grid-template-columns:repeat(2,minmax(0,1fr));}@media(max-width:560px){grid-template-columns:1fr;}`,
  statistic: css`border-top:2px solid #38475b;background:#121925;padding:${theme.spacing(1.25)};min-height:108px;`,
  statLabel: css`color:#9eacbd;font-size:12px;`,
  statValue: css`margin-top:${theme.spacing(1)};font-size:25px;line-height:1;font-weight:700;color:#f0f4fa;`,
  statDetail: css`margin-top:${theme.spacing(1)};font-size:11px;color:#8190a4;`,
  split: css`display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.75fr);gap:${theme.spacing(1.5)};@media(max-width:1000px){grid-template-columns:1fr;}`,
  panel: css`border:1px solid #2b3647;background:#121925;padding:${theme.spacing(1.5)};`,
  panelHeader: css`display:flex;align-items:flex-start;justify-content:space-between;gap:${theme.spacing(1)};margin-bottom:${theme.spacing(1.25)};`,
  panelTitle: css`font-size:14px;font-weight:700;color:#f0f4fa;`,
  panelSub: css`margin-top:3px;color:#8795a7;font-size:11px;`,
  smallLabel: css`color:#8795a7;font-size:10px;text-transform:uppercase;`,
  smallValue: css`margin-top:3px;color:#eff4fa;font-size:13px;font-weight:700;`,
  heatGrid: css`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:${theme.spacing(.75)};@media(max-width:560px){grid-template-columns:repeat(2,minmax(0,1fr));}`,
  channel: css`border:1px solid #2c3748;border-left:3px solid currentColor;background:#0e141e;padding:${theme.spacing(1)};text-align:left;cursor:pointer;min-height:86px;transition:background .15s,transform .15s;&:hover{background:#172130;transform:translateY(-1px);}&:disabled{cursor:not-allowed;opacity:.72;}&:disabled:hover{background:#0e141e;transform:none;}`,
  channelSelected: css`box-shadow:inset 0 0 0 1px #4aa3ff;background:#142235;`,
  channelTop: css`display:flex;justify-content:space-between;color:#e8eff8;font-size:12px;font-weight:700;`,
  channelValue: css`display:block;margin-top:${theme.spacing(1)};color:#e9eff7;font-size:13px;font-weight:700;`,
  channelMeta: css`display:block;margin-top:3px;color:#8f9eb0;font-size:11px;`,
  list: css`display:grid;gap:0;`,
  row: css`display:grid;grid-template-columns:minmax(0,1fr) auto;gap:${theme.spacing(1)};align-items:center;border-top:1px solid #2a3444;padding:${theme.spacing(1.1,0)};text-align:left;background:transparent;color:inherit;`,
  rowButton: css`width:100%;border:0;cursor:pointer;&:hover .exceptionName{color:#81baff;}`,
  exceptionName: css`font-size:13px;font-weight:700;color:#e9eff8;`,
  exceptionMeta: css`margin-top:3px;color:#8795a7;font-size:11px;`,
  status: css`border:1px solid currentColor;padding:3px 6px;font-size:10px;font-weight:700;white-space:nowrap;`,
  event: css`display:grid;grid-template-columns:74px 88px minmax(0,1fr);gap:${theme.spacing(1)};border-top:1px solid #2a3444;padding:${theme.spacing(1.1,0)};font-size:12px;@media(max-width:560px){grid-template-columns:60px 1fr;}.eventDetail{color:#8997a9;}.eventKind{color:#dfe8f3;font-weight:600;}`,
  queue: css`display:grid;grid-template-columns:minmax(230px,.8fr) minmax(0,1.35fr) minmax(250px,.85fr);gap:${theme.spacing(1.5)};@media(max-width:1150px){grid-template-columns:1fr;}`,
  queueItem: css`width:100%;border:0;border-top:1px solid #2a3444;background:transparent;color:inherit;padding:${theme.spacing(1.1,0)};text-align:left;cursor:pointer;&:hover{background:#172130;}&:first-child{border-top:0;}`,
  queueItemActive: css`box-shadow:inset 3px 0 #4aa3ff;padding-left:${theme.spacing(1)};`,
  facts: css`display:grid;grid-template-columns:1fr 1fr;gap:${theme.spacing(1)};margin-top:${theme.spacing(1.5)};`,
  fact: css`border-top:1px solid #2c3748;padding-top:${theme.spacing(.75)};`,
  actionList: css`display:grid;gap:${theme.spacing(.75)};`,
  note: css`margin-top:${theme.spacing(1.5)};border-left:2px solid #4aa3ff;padding:${theme.spacing(.5,0,.5,1)};color:#aeb9c9;font-size:12px;line-height:1.55;`,
  muted: css`color:#8795a7;font-size:12px;`,
  diagnosticHeader: css`display:flex;align-items:flex-end;justify-content:space-between;gap:${theme.spacing(1.5)};flex-wrap:wrap;`,
  entityName: css`margin-top:3px;font-size:28px;font-weight:700;color:#f2f6fa;`,
  detailStrip: css`display:flex;gap:${theme.spacing(2)};flex-wrap:wrap;color:#a8b5c6;font-size:12px;`,
  readingBar: css`display:flex;align-items:baseline;justify-content:space-between;gap:${theme.spacing(1.5)};border-top:1px solid #2a3444;border-bottom:1px solid #2a3444;padding:${theme.spacing(1,0)};`,
  readingValue: css`color:#f3f7fb;font-size:22px;font-weight:700;`,
  readingMeta: css`color:#8d9caf;font-size:11px;text-align:right;`,
  trend: css`height:272px;overflow:hidden;border-bottom:1px solid #2a3444;padding:${theme.spacing(1,0,0)};box-sizing:border-box;`,
  trendSvg: css`display:block;width:100%;height:100%;overflow:hidden;`,
  trendCaption: css`display:flex;justify-content:space-between;gap:${theme.spacing(1)};padding-top:${theme.spacing(.75)};color:#8291a5;font-size:11px;`,
  gridLine: css`stroke:#2d394a;stroke-width:.35;`,
  voltageLine: css`fill:none;stroke:#5ba9ff;stroke-width:1.1;vector-effect:non-scaling-stroke;`,
  tempLine: css`fill:none;stroke:#f2a55b;stroke-width:1.1;vector-effect:non-scaling-stroke;`,
  currentLine: css`fill:none;stroke:#67d39c;stroke-width:1.1;vector-effect:non-scaling-stroke;`,
  focusedLine: css`fill:none;stroke:#5fd39b;stroke-width:2;stroke-linejoin:round;stroke-linecap:round;vector-effect:non-scaling-stroke;`,
  attentionLine: css`stroke:#e9b05d;stroke-width:1;stroke-dasharray:5 4;vector-effect:non-scaling-stroke;`,
  criticalLine: css`stroke:#ff7188;stroke-width:1;stroke-dasharray:5 4;vector-effect:non-scaling-stroke;`,
  axisText: css`fill:#8291a5;font-size:10px;`,
  nextAction: css`display:grid;gap:${theme.spacing(.75)};border-left:3px solid #5fd39b;padding:${theme.spacing(.25,0,.25,1)};`,
  nextActionTitle: css`color:#edf3fa;font-size:15px;font-weight:700;`,
  empty: css`padding:${theme.spacing(3,0)};color:#8795a7;font-size:13px;`,
});

export type OperationsStyles = ReturnType<typeof getOperationsStyles>;
